/* Glossary: plain-English definitions. `module` links each term to where it's taught. */
window.GLOSSARY = [
  // Module 1 · How the Web Works
  { term: 'Internet', module: 'm1', def: 'A worldwide network of connected computers. The web is one of the things that runs on it, alongside email, video calls, and games.' },
  { term: 'World Wide Web', module: 'm1', def: 'All the web pages and sites you can visit in a browser, linked together by hyperlinks.' },
  { term: 'Website', module: 'm1', def: 'A collection of related web pages (files) published under one domain name.' },
  { term: 'Browser', module: 'm1', def: 'The app you use to visit websites, like Chrome, Safari, Firefox, or Edge. It requests pages and displays them.' },
  { term: 'Client', module: 'm1', def: 'The side of a conversation that asks for something. On the web, your browser is the client.' },
  { term: 'Server', module: 'm1', def: 'A computer that stores website files and sends them to browsers when they ask. It is usually kept running 24/7 in a data centre.' },
  { term: 'Data centre', module: 'm1', def: 'A building full of servers with fast internet connections, backup power, and cooling.' },
  { term: 'Request', module: 'm1', def: 'A message from a browser to a server asking for something, such as a page, an image, or to save form data.' },
  { term: 'Response', module: 'm1', def: 'The server’s reply to a request: a status code plus the requested content.' },
  { term: 'Status code', module: 'm1', def: 'A three-digit number in a server response that says how things went. 200 = OK, 404 = Not Found, 500 = Server Error.' },
  { term: '404', module: 'm1', def: 'The “Not Found” status code. The server is working, but there is nothing at that address.' },
  { term: 'IP address', module: 'm1', def: 'A number that identifies a computer on the internet, such as 93.184.215.14. Like a phone number for computers.' },
  { term: 'Domain name', module: 'm1', def: 'A human-friendly name for a website, such as example.com, that points to an IP address. You rent one yearly from a registrar.' },
  { term: 'DNS', module: 'm1', def: 'Domain Name System: the internet’s “contacts app” that translates domain names into IP addresses.' },
  { term: 'Nameserver', module: 'm1', def: 'A DNS server that holds the official records for a domain, saying which IP address it points to.' },
  { term: 'TLD (top-level domain)', module: 'm1', def: 'The ending of a domain name, like .com, .org, .dev, or .uk.' },
  { term: 'Subdomain', module: 'm1', def: 'A prefix that creates a separate section of a domain, like blog.example.com or shop.example.com.' },
  { term: 'URL', module: 'm1', def: 'Uniform Resource Locator: a full web address, including protocol, domain, and path, such as https://example.com/about.' },
  { term: 'Path', module: 'm1', def: 'The part of a URL after the domain that says which page or file you want, such as /blog/first-post.' },
  { term: 'Protocol', module: 'm1', def: 'An agreed set of rules for how computers communicate. HTTP and HTTPS are the protocols of the web.' },
  { term: 'HTTP', module: 'm1', def: 'HyperText Transfer Protocol: the rules browsers and servers use to send requests and responses.' },
  { term: 'HTTPS', module: 'm1', def: 'The secure, encrypted version of HTTP. Shown with a padlock icon in the address bar.' },
  { term: 'Encryption', module: 'm1', def: 'Scrambling data so only the intended sender and receiver can read it.' },
  { term: 'SSL/TLS certificate', module: 'm1', def: 'A digital ID that proves a website is who it claims to be and enables HTTPS. Free from services like Let’s Encrypt.' },
  { term: 'GET', module: 'm1', def: 'The HTTP method for fetching something, used every time you load a page.' },
  { term: 'POST', module: 'm1', def: 'The HTTP method for sending data to a server, such as submitting a form.' },
  { term: 'Hosting', module: 'm1', def: 'Renting space on an always-on server so your website can be reached by anyone online.' },
  { term: 'Static website', module: 'm1', def: 'A site made of ready-made files that are the same for every visitor. Often hosted for free.' },
  { term: 'Dynamic website', module: 'm1', def: 'A site whose pages are built on the fly for each visitor, often using a database.' },

  // Module 2 · Setting Up
  { term: 'Code editor', module: 'm2', def: 'An app for writing code, with features like syntax colours and autocomplete. VS Code is the most popular.' },
  { term: 'VS Code', module: 'm2', def: 'Visual Studio Code: a free, popular code editor from Microsoft for Mac, Windows, and Linux.' },
  { term: 'Extension', module: 'm2', def: 'An add-on that gives your code editor (or browser) new features, like Live Server or Prettier.' },
  { term: 'Live Server', module: 'm2', def: 'A VS Code extension that opens your page in a browser and reloads it automatically when you save.' },
  { term: 'Emmet', module: 'm2', def: 'A shortcut tool built into VS Code. Type ! then Tab in an HTML file to get a full starter template.' },
  { term: 'Project folder', module: 'm2', def: 'The main (root) folder containing all of a website’s files.' },
  { term: 'index.html', module: 'm2', def: 'The standard file name for a homepage. Servers show it automatically when no specific page is requested.' },
  { term: 'File extension', module: 'm2', def: 'The ending of a file name, like .html, .css, .js, or .jpg, that says what kind of file it is.' },
  { term: 'Relative path', module: 'm2', def: 'Directions to a file starting from the current file, such as images/me.jpg or ../index.html.' },
  { term: 'Absolute URL', module: 'm2', def: 'A complete address including the protocol and domain, such as https://example.com/images/me.jpg.' },
  { term: 'DevTools', module: 'm2', def: 'Developer tools built into every browser for inspecting HTML and CSS, viewing errors, and watching network requests.' },
  { term: 'Console', module: 'm2', def: 'The DevTools panel that shows messages and errors from JavaScript, and lets you run code.' },
  { term: 'console.log()', module: 'm2', def: 'A JavaScript command that prints a message to the console, handy for checking what your code is doing.' },
  { term: 'Terminal', module: 'm2', def: 'A text-based way to control your computer by typing commands. Also called the command line.' },

  // Module 3 · HTML
  { term: 'HTML', module: 'm3', def: 'HyperText Markup Language: the language that gives web pages their structure and content.' },
  { term: 'Tag', module: 'm3', def: 'A label in angle brackets, like <p> or </p>, that marks where an element starts or ends.' },
  { term: 'Element', module: 'm3', def: 'A complete piece of HTML: the opening tag, the content, and the closing tag together.' },
  { term: 'Attribute', module: 'm3', def: 'Extra information inside an opening tag, written as name="value", like href="about.html".' },
  { term: 'Void element', module: 'm3', def: 'An element with no content and no closing tag, like <img>, <br>, or <meta>.' },
  { term: 'Nesting', module: 'm3', def: 'Placing elements inside other elements. Tags must close in the reverse order they opened.' },
  { term: 'DOCTYPE', module: 'm3', def: 'The first line of an HTML file (<!DOCTYPE html>), telling the browser it’s a modern HTML page.' },
  { term: '<head>', module: 'm3', def: 'The part of an HTML document holding information about the page (title, character set, links to CSS) that isn’t shown directly.' },
  { term: '<body>', module: 'm3', def: 'The part of an HTML document holding everything visible on the page.' },
  { term: 'Meta tag', module: 'm3', def: 'A tag in the head that gives the browser information about the page, like the character set or viewport settings.' },
  { term: 'Viewport', module: 'm3', def: 'The visible area of a web page on a screen. The viewport meta tag makes pages display properly on phones.' },
  { term: 'Comment', module: 'm3', def: 'A note in code for humans that the browser ignores. In HTML: <!-- like this -->.' },
  { term: 'Heading', module: 'm3', def: 'A title element, from <h1> (most important) to <h6> (least). Use one <h1> per page.' },
  { term: 'Whitespace collapsing', module: 'm3', def: 'HTML treats any run of spaces and line breaks as a single space.' },
  { term: 'Hyperlink', module: 'm3', def: 'A clickable link to another page, site, or section, made with the <a> tag and its href attribute.' },
  { term: 'href', module: 'm3', def: 'The attribute that holds a link’s destination.' },
  { term: 'Anchor link', module: 'm3', def: 'A link like href="#contact" that jumps to the element with that id on the same page.' },
  { term: 'id', module: 'm3', def: 'An attribute that gives an element a unique name on the page. Used for anchor links, labels, CSS, and JavaScript.' },
  { term: 'src', module: 'm3', def: 'The “source” attribute that says where a file (like an image) is located.' },
  { term: 'Alt text', module: 'm3', def: 'A text description of an image, read by screen readers and shown if the image fails to load.' },
  { term: 'SVG', module: 'm3', def: 'Scalable Vector Graphics: an image format made of shapes, so it stays sharp at any size. Ideal for logos and icons.' },
  { term: 'WebP', module: 'm3', def: 'A modern image format that is much smaller than JPG or PNG at similar quality.' },
  { term: 'Unordered list', module: 'm3', def: 'A bulleted list, made with <ul> and <li> items, for when order doesn’t matter.' },
  { term: 'Ordered list', module: 'm3', def: 'A numbered list, made with <ol> and <li> items, for when order matters.' },
  { term: 'Form', module: 'm3', def: 'A group of fields (inputs, dropdowns, buttons) for collecting information from visitors.' },
  { term: 'Input', module: 'm3', def: 'A form field. Its type attribute (text, email, password, checkbox…) controls how it behaves.' },
  { term: 'Label', module: 'm3', def: 'The visible name of a form field. Connected to its input by matching for and id attributes.' },
  { term: 'Validation', module: 'm3', def: 'Checking form data before it’s sent, such as making sure required fields are filled and emails contain @.' },
  { term: 'Semantic HTML', module: 'm3', def: 'Using tags that describe what content is (like <nav>, <main>, <footer>) rather than generic boxes.' },
  { term: '<div>', module: 'm3', def: 'A generic container with no meaning, used for grouping and styling when no semantic tag fits.' },
  { term: 'Screen reader', module: 'm3', def: 'Software that reads web pages aloud for blind and visually impaired people.' },

  // Module 4 · CSS
  { term: 'CSS', module: 'm4', def: 'Cascading Style Sheets: the language that controls how web pages look, including colours, fonts, spacing, and layout.' },
  { term: 'Rule (CSS)', module: 'm4', def: 'A selector plus a block of declarations, e.g. h1 { color: red; }.' },
  { term: 'Selector', module: 'm4', def: 'The part of a CSS rule that chooses which elements to style, like p, .card, or #hero.' },
  { term: 'Property', module: 'm4', def: 'The aspect of an element a CSS declaration changes, such as color, margin, or font-size.' },
  { term: 'Declaration', module: 'm4', def: 'One property: value; pair inside a CSS rule.' },
  { term: 'Class', module: 'm4', def: 'A reusable label added to elements with class="...", targeted in CSS with a dot (.card).' },
  { term: 'Specificity', module: 'm4', def: 'How CSS decides which rule wins when several target the same element: IDs beat classes, and classes beat element types.' },
  { term: 'Cascade', module: 'm4', def: 'The rules for combining conflicting CSS. When specificity is equal, the later rule wins.' },
  { term: 'Pseudo-class', module: 'm4', def: 'A selector for an element in a particular state, such as :hover, :focus-visible, or :first-child.' },
  { term: 'Hex code', module: 'm4', def: 'A colour written as # plus six hexadecimal digits for red, green, and blue, e.g. #4f46e5.' },
  { term: 'Contrast ratio', module: 'm4', def: 'How different text and background brightness are. Aim for at least 4.5 : 1 for normal text.' },
  { term: 'rem', module: 'm4', def: 'A CSS unit relative to the root font size (usually 16px), so 2rem = 32px. Respects users’ text-size settings.' },
  { term: 'Box model', module: 'm4', def: 'The idea that every element is a box made of content, padding, border, and margin.' },
  { term: 'Padding', module: 'm4', def: 'Space inside an element, between its content and its border.' },
  { term: 'Margin', module: 'm4', def: 'Space outside an element’s border, pushing other elements away.' },
  { term: 'box-sizing', module: 'm4', def: 'With border-box, an element’s width includes its padding and border, which makes sizing predictable.' },
  { term: 'Flexbox', module: 'm4', def: 'A CSS layout method for arranging items in a single row or column, with easy spacing and alignment.' },
  { term: 'CSS Grid', module: 'm4', def: 'A CSS layout method for arranging items in rows and columns at the same time.' },
  { term: 'fr unit', module: 'm4', def: 'A Grid unit meaning “one fraction of the free space”, as in 1fr 2fr.' },
  { term: 'Media query', module: 'm4', def: 'A CSS block that applies only under certain conditions, usually a minimum screen width: @media (min-width: 700px).' },
  { term: 'Breakpoint', module: 'm4', def: 'A screen width where the layout changes, set with a media query.' },
  { term: 'Responsive design', module: 'm4', def: 'Designing pages that adapt to any screen size, from phones to big monitors.' },

  // Module 5 · JavaScript
  { term: 'JavaScript', module: 'm5', def: 'The programming language of the web, used to make pages interactive.' },
  { term: 'Variable', module: 'm5', def: 'A named container for a value. Created with const (can’t be reassigned) or let (can change).' },
  { term: 'String', module: 'm5', def: 'A piece of text in JavaScript, written in quotes: "hello".' },
  { term: 'Boolean', module: 'm5', def: 'A value that is either true or false.' },
  { term: 'Array', module: 'm5', def: 'An ordered list of values, like ["a", "b", "c"]. Counting starts at 0.' },
  { term: 'Object', module: 'm5', def: 'A group of named values (properties), like { name: "Sam", age: 29 }.' },
  { term: 'Template literal', module: 'm5', def: 'A string written with backticks that can include variables using ${...}.' },
  { term: 'Function', module: 'm5', def: 'A reusable, named block of code that can take parameters and return a value.' },
  { term: 'Parameter', module: 'm5', def: 'A placeholder name in a function definition for a value passed in when the function is called.' },
  { term: 'Arrow function', module: 'm5', def: 'A shorter way to write a function: (x) => x * 2.' },
  { term: 'Conditional', module: 'm5', def: 'Code that runs only if a condition is true, written with if / else.' },
  { term: 'Loop', module: 'm5', def: 'Code that repeats, such as a for loop or array.forEach().' },
  { term: 'Event', module: 'm5', def: 'Something that happens on the page, like a click, key press, or form submit.' },
  { term: 'Event listener', module: 'm5', def: 'A function attached with addEventListener that runs whenever a particular event happens.' },
  { term: 'DOM', module: 'm5', def: 'Document Object Model: the browser’s live, tree-shaped version of your HTML that JavaScript can read and change.' },
  { term: 'querySelector', module: 'm5', def: 'A JavaScript method that finds the first element matching a CSS selector.' },
  { term: 'classList', module: 'm5', def: 'A way to add, remove, or toggle an element’s CSS classes from JavaScript.' },
  { term: 'localStorage', module: 'm5', def: 'Browser storage that keeps small bits of data (like a theme choice) between visits, on that device only.' },

  // Module 6 · Project
  { term: 'Sitemap', module: 'm6', def: 'A list of all the pages on a site and how they connect. Also an XML file that helps search engines.' },
  { term: 'Wireframe', module: 'm6', def: 'A rough grey-box sketch of a page layout, made before designing or coding.' },
  { term: 'CSS custom property', module: 'm6', def: 'A CSS variable, defined like --color-accent: purple; and used with var(--color-accent).' },
  { term: 'Hero section', module: 'm6', def: 'The large introductory area at the top of a home page, usually with a headline and a button.' },
  { term: 'Call to action (CTA)', module: 'm6', def: 'A prominent button or link that tells visitors what to do next, like “Contact me”.' },
  { term: 'Favicon', module: 'm6', def: 'The small icon shown on a browser tab and in bookmarks.' },

  // Module 7 · Best practices
  { term: 'Accessibility (a11y)', module: 'm7', def: 'Making websites usable by everyone, including people with disabilities. “a11y” is short for the 11 letters between a and y.' },
  { term: 'ARIA', module: 'm7', def: 'Attributes (like aria-label or aria-expanded) that give extra information to assistive technology. Use native HTML first.' },
  { term: 'Skip link', module: 'm7', def: 'A link, hidden until focused, that lets keyboard users jump past the navigation to the main content.' },
  { term: 'Focus', module: 'm7', def: 'The element currently selected for keyboard input. It should always be visibly highlighted.' },
  { term: 'SEO', module: 'm7', def: 'Search Engine Optimisation: making your site easy for search engines like Google to find and understand.' },
  { term: 'Meta description', module: 'm7', def: 'A short summary in <meta name="description"> that often appears under your link in search results.' },
  { term: 'Open Graph', module: 'm7', def: 'Meta tags (og:title, og:image…) that control how a link preview looks when shared.' },
  { term: 'Crawler', module: 'm7', def: 'A program that search engines use to discover and read web pages by following links.' },
  { term: 'Lazy loading', module: 'm7', def: 'Delaying an image’s download until it’s about to scroll into view, with loading="lazy".' },
  { term: 'CDN', module: 'm7', def: 'Content Delivery Network: copies of your files on servers around the world, so they load quickly everywhere.' },
  { term: 'Lighthouse', module: 'm7', def: 'A tool built into Chrome DevTools that scores performance, accessibility, best practices, and SEO.' },
  { term: 'Core Web Vitals', module: 'm7', def: 'Google’s key user-experience measurements: loading speed (LCP), responsiveness (INP), and visual stability (CLS).' },
  { term: 'Mobile-first', module: 'm7', def: 'Designing and writing CSS for small screens first, then enhancing for larger screens.' },

  // Module 8 · Git
  { term: 'Git', module: 'm8', def: 'A version-control tool that saves snapshots of your code so you can track changes and undo mistakes.' },
  { term: 'GitHub', module: 'm8', def: 'A website for storing Git projects online, sharing code, and collaborating. It can also host static sites.' },
  { term: 'Version control', module: 'm8', def: 'A system for recording changes to files over time so you can review or restore earlier versions.' },
  { term: 'Repository (repo)', module: 'm8', def: 'A project folder tracked by Git, including its full history.' },
  { term: 'Commit', module: 'm8', def: 'A saved snapshot of your project in Git, with a message describing the change.' },
  { term: 'Staging area', module: 'm8', def: 'Where you place changes with git add before committing them.' },
  { term: 'Branch', module: 'm8', def: 'A separate line of development in Git, so you can work on something without affecting main.' },
  { term: 'Merge', module: 'm8', def: 'Combining the changes from one branch into another.' },
  { term: 'Merge conflict', module: 'm8', def: 'When two branches changed the same lines, and Git needs you to choose what to keep.' },
  { term: 'Remote', module: 'm8', def: 'A copy of a repository stored elsewhere, usually on GitHub, typically named origin.' },
  { term: 'Push', module: 'm8', def: 'Uploading your local commits to a remote repository (git push).' },
  { term: 'Pull', module: 'm8', def: 'Downloading new commits from a remote repository into your local one (git pull).' },
  { term: 'Clone', module: 'm8', def: 'Copying an existing repository from GitHub onto your computer (git clone).' },
  { term: 'Pull request', module: 'm8', def: 'A GitHub page proposing that one branch be merged into another, where others can review the changes.' },
  { term: '.gitignore', module: 'm8', def: 'A file listing files and folders Git should not track, like system junk or secrets.' },
  { term: 'README', module: 'm8', def: 'A file (usually README.md) that explains what a project is. GitHub shows it on the repository’s front page.' },
  { term: 'Markdown', module: 'm8', def: 'A simple text formatting language using symbols like # for headings and ** for bold.' },

  // Module 9 · Going live
  { term: 'Deploy', module: 'm9', def: 'To publish your website so it’s live on the internet.' },
  { term: 'GitHub Pages', module: 'm9', def: 'GitHub’s free hosting for static websites, published straight from a repository.' },
  { term: 'Netlify', module: 'm9', def: 'A popular free host for static sites with drag-and-drop deploys, continuous deployment, and built-in forms.' },
  { term: 'Vercel', module: 'm9', def: 'A popular free host for static sites and front-end frameworks, with automatic deploys and previews.' },
  { term: 'Continuous deployment', module: 'm9', def: 'Automatically publishing a new version of your site whenever you push to Git.' },
  { term: 'Deploy preview', module: 'm9', def: 'A temporary live URL for a branch or pull request, so you can test changes before merging.' },
  { term: 'Registrar', module: 'm9', def: 'A company you rent domain names from, such as Cloudflare, Porkbun, or Namecheap.' },
  { term: 'WHOIS privacy', module: 'm9', def: 'A registrar service that hides your personal contact details from the public domain record.' },
  { term: 'A record', module: 'm9', def: 'A DNS record that points a domain name to an IPv4 address.' },
  { term: 'CNAME record', module: 'm9', def: 'A DNS record that points a name (like www) to another domain name.' },
  { term: 'Apex domain', module: 'm9', def: 'The bare domain without a subdomain, like example.com. Written as @ in DNS settings.' },
  { term: 'DNS propagation', module: 'm9', def: 'The time it takes for DNS changes to spread across the internet: minutes to a few hours.' },
  { term: 'Let’s Encrypt', module: 'm9', def: 'A free certificate authority that provides the HTTPS certificates most hosts use.' },
  { term: 'Mixed content', module: 'm9', def: 'An HTTPS page loading resources over insecure HTTP, which browsers warn about or block.' },
  { term: 'Honeypot field', module: 'm9', def: 'A hidden form field that people never fill in but spam bots do, used to filter spam.' },

  // Module 10 · Next steps
  { term: 'Framework', module: 'm10', def: 'A ready-made toolkit (like React) that gives structure and shortcuts for building bigger apps.' },
  { term: 'React', module: 'm10', def: 'A popular JavaScript library for building user interfaces from reusable components.' },
  { term: 'Component', module: 'm10', def: 'A reusable, self-contained piece of user interface.' },
  { term: 'JSX', module: 'm10', def: 'HTML-like syntax used inside JavaScript in React components.' },
  { term: 'State', module: 'm10', def: 'Data in an app that can change over time. React re-draws the page when it changes.' },
  { term: 'Front-end', module: 'm10', def: 'The part of a website that runs in the browser: HTML, CSS, and JavaScript.' },
  { term: 'Back-end', module: 'm10', def: 'Code that runs on a server: storing data, checking logins, handling payments.' },
  { term: 'Full-stack', module: 'm10', def: 'Working on both the front-end and the back-end.' },
  { term: 'API', module: 'm10', def: 'Application Programming Interface: an agreed way for programs to talk to each other, often a URL that returns data.' },
  { term: 'JSON', module: 'm10', def: 'JavaScript Object Notation: a text format for data that looks like JavaScript objects and arrays.' },
  { term: 'fetch()', module: 'm10', def: 'The browser’s built-in JavaScript function for requesting data from a URL.' },
  { term: 'Database', module: 'm10', def: 'An organised store of data on a server that many users can read and write.' },
  { term: 'SQL', module: 'm10', def: 'Structured Query Language: the language for querying relational databases (SELECT, INSERT…).' },
  { term: 'Serverless function', module: 'm10', def: 'A small piece of back-end code that runs on demand, without you managing a server.' },
  { term: 'Node.js', module: 'm10', def: 'A program that runs JavaScript outside the browser, on computers and servers.' },
  { term: 'npm', module: 'm10', def: 'Node Package Manager: installs code packages shared by other developers.' },
  { term: 'Vite', module: 'm10', def: 'A fast build tool and development server for modern web projects.' },
  { term: 'TypeScript', module: 'm10', def: 'JavaScript with types, which lets your editor catch many mistakes before the code runs.' },
  { term: 'Tailwind CSS', module: 'm10', def: 'A CSS framework where you style elements with small utility classes in your HTML.' },
];
